CC=gcc
CFLAGS=-std=c99 -O1 -march=native -I../ref -static -fopenmp 
LIBS=
FILES=b2sum.c ../ref/blake2b-ref.c ../ref/blake2s-ref.c ../ref/blake2bp-ref.c ../ref/blake2sp-ref.c 
#FILES=b2sum.c ../sse/blake2b.c ../sse/blake2s.c ../sse/blake2bp.c ../sse/blake2sp.c 
all: $(FILES)
	$(CC) $(FILES) $(CFLAGS) $(LIBS) -o b2sum 

clean:	
	rm -f b2sum
